export const LATEST_SUPPORT_SWAGGER_JSDOC_VERSION = "^6.2.8";
export const LATEST_SUPPORT_SWAGGER_JSDOC_DEV_VERSION = "^6.0.4";

export const LATEST_SUPPORT_SWAGGER_UI_VERSION = "^5.0.1";
export const LATEST_SUPPORT_SWAGGER_UI_DEV_VERSION = "^4.1.7";